In [1]:
import pandas as pd
import matplotlib as plt
import numpy as np
import seaborn as sns

In [ ]:
#Q1
pd.__version__

'3.0.6'

In [ ]:
#Q2 Records count
!wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv

--2026-09-28 12:46:39--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.109.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 874188 (854K) [text/plain]
Saving to: ‘car_fuel_efficiency.csv’

car_fuel_efficiency 100%[===================>] 853.70K   854KB/s    in 1.0s

2026-09-28 12:46:41 (854 KB/s) - ‘car_fuel_efficiency.csv’ saved [874188/874188]

In [6]:
car_fuel = pd.read_csv('/home/ron/projects/ml-zoomcamp-homework/1.homework/car_fuel_efficiency.csv')
car_fuel.head()

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
0,170,3.0,159.0,3413.433759,17.7,2003,Europe,Gasoline,All-wheel drive,0.0,13.231729
1,130,5.0,97.0,3149.664934,17.8,2007,USA,Gasoline,Front-wheel drive,0.0,13.688217
2,170,NaN,78.0,3079.038997,15.1,2018,Europe,Gasoline,Front-wheel drive,0.0,14.246341
3,220,4.0,NaN,2542.392402,20.2,2009,USA,Diesel,All-wheel drive,2.0,16.912736
4,210,1.0,140.0,3460.870990,14.4,2009,Europe,Gasoline,All-wheel drive,2.0,12.488369

In [7]:
car_fuel.describe()

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,num_doors,fuel_efficiency_mpg
count,9704.000000,9222.000000,8996.000000,9704.000000,8774.000000,9704.000000,9202.000000,9704.000000
mean,199.708368,3.962481,149.657292,3001.280993,15.021928,2011.484027,-0.006412,14.985243
std,49.455319,1.999323,29.879555,497.894860,2.510339,6.659808,1.048162,2.556468
min,10.000000,0.000000,37.000000,952.681761,6.000000,2000.000000,-4.000000,6.200971
25%,170.000000,3.000000,130.000000,2666.248985,13.300000,2006.000000,-1.000000,13.267459
50%,200.000000,4.000000,149.000000,2993.226296,15.000000,2012.000000,0.000000,15.006037
75%,230.000000,5.000000,170.000000,3334.957039,16.700000,2017.000000,1.000000,16.707965
max,380.000000,13.000000,271.000000,4739.077089,24.300000,2023.000000,4.000000,25.967222

In [10]:
#Q3 Fuel types
car_fuel['fuel_type'].unique()

<StringArray>
['Gasoline', 'Diesel']
Length: 2, dtype: str

In [18]:
#Q4. Missing values
print(car_fuel.isnull().sum())
print([car_fuel.isnull().sum() > 0])

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64
[engine_displacement    False
num_cylinders           True
horsepower              True
vehicle_weight         False
acceleration            True
model_year             False
origin                 False
fuel_type              False
drivetrain             False
num_doors               True
fuel_efficiency_mpg    False
dtype: bool]

In [22]:
#Q5. Max fuel efficiency
#What's the maximum fuel efficiency of cars from Asia?

car_fuel[car_fuel['origin'] == 'Asia']['fuel_efficiency_mpg'].max()

np.float64(23.759122836520497)

In [25]:
"""Q6. Median value of horsepower
Find the median value of the horsepower column in the dataset.
Next, calculate the most frequent value of the same horsepower column.
Use the fillna method to fill the missing values in the horsepower column with the most frequent value from the previous step.
Now, calculate the median value of horsepower once again.
Has it changed?

Yes, it increased
Yes, it decreased
No"""

print(car_fuel['horsepower'].median())
print(car_fuel['horsepower'].mode()[0])
car_fuel['horsepower'].fillna(car_fuel['horsepower'].mode()[0])
print(car_fuel['horsepower'].median())

149.0
152.0
149.0

In [26]:
"""Q7. Sum of weights
Select all the cars from Asia
Select only columns vehicle_weight and model_year
Select the first 7 values
Get the underlying NumPy array. Let's call it X.
Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
Invert XTX.
Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].
Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
What's the sum of all the elements of the result?
"""

asia = car_fuel[car_fuel['origin'] == 'Asia']

X = asia[['vehicle_weight', 'model_year']].head(7).to_numpy()
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

XTX = X.T.dot(X)
XTX_inv = np.linalg.inv(XTX)
w = XTX_inv.dot(X.T).dot(y)

print(w)
print(w.sum())

[0.01386421 0.5049067 ]
0.5187709081074016